# ====================================
# ASTRO SESSION ANALYSER - EXAMPLE CONFIG
# Complete configuration template with all supported parameters
# ====================================

# Discord webhook URL for sending summaries (REQUIRED)
webhook: "https://discord.com/api/webhooks/example/test"

# Time window in hours to analyze sessions
hours: 48

# Path to Ekos analyze files 
# Default paths:
#   - Native KStars: ~/.local/share/kstars/analyze
#   - Flatpak KStars: ~/.var/app/org.kde.kstars/data/kstars/analyze
analyze_dir: "/home/grm/.var/app/org.kde.kstars/data/kstars/analyze"

# Basic log level (DEBUG, INFO, WARNING, ERROR)
log_level: "INFO"

# ====================================
# REPORTING CONFIGURATION
# ====================================

# Discord report level: minimal, standard, detailed
# - minimal: Ultra-quick notifications with conditions & autofocus
# - standard: Current balanced format (default) 
# - detailed: Comprehensive analysis with correlations (auto-enables advanced analytics)
discord_report_level: "standard"

# ====================================
# PLOTTING CONFIGURATION
# ====================================

# Enable temporal plotting
plotting:
  enabled: true
  output_dir: "./plots"
  # Keep plots after dry-run for inspection (optional)
  cleanup_after_dry_run: true

# ====================================
# IMAGING SETUP CONFIGURATION
# ====================================

# Pixel scale configuration for accurate guiding assessment
# This significantly improves guiding quality calculation accuracy
imaging_setup:
  # Pixel scale in arcseconds per pixel
  # Calculate as: (206265 * pixel_size_um) / (focal_length_mm * binning)
  # Examples:
  #   - Celestron C8 (f/6.3, 1600mm) + ASI183MC (2.4μm): 0.31"/pixel
  #   - 200mm lens (f/2.8) + Canon DSLR (4.3μm): 4.43"/pixel  
  #   - Takahashi FSQ85 (450mm) + ASI294MC (4.63μm): 2.12"/pixel
  pixel_scale_arcsec: 1.0  # CHANGE THIS to match your setup
  
  # Optional: Equipment names for logging (informational only)
  telescope: "Unknown Telescope"
  camera: "Unknown Camera" 

# ====================================
# ALERT THRESHOLDS
# ====================================

# Automatic alert thresholds
alert_thresholds:
  # HFR drift warning (pixels)
  hfr_drift_warning: 0.5
  
  # Temperature swing warning (°C)
  temperature_swing_warning: 5.0
  
  # Success rate warning (0.0-1.0)
  success_rate_warning: 0.8
  
  # Minimum stars for quality warning
  min_stars_warning: 100
  
  # Guide quality thresholds (in pixels - much more accurate!)
  # These replace the old fixed arcsecond thresholds
  guide_quality:
    excellent_px: 0.5    # < 0.5 pixels = Excellent
    good_px: 1.0         # < 1.0 pixels = Good  
    average_px: 1.5      # < 1.5 pixels = Average
    # > 1.5 pixels = Poor

# ====================================
# NOTIFICATION PREFERENCES
# ====================================

notifications:
  # Send alerts for poor performance
  performance_alerts: true
  
  # Send summary only if captures > threshold
  min_captures_for_report: 1
  
  # Include quality score in reports (requires advanced_analytics)
  include_quality_score: true

# ====================================
# ADVANCED ANALYTICS (for detailed level)
# Automatically enabled for 'detailed' level
# Requires: pip install numpy scipy
# ====================================

# Analytics are automatically enabled for detailed level
# No need to configure - everything is included in detailed mode

# ====================================
# QUICK MODE EXAMPLES
# ====================================

# To switch quickly between modes:

# MINIMAL MODE (quick notifications):
# discord_report_level: "minimal"

# STANDARD MODE (balanced):
# discord_report_level: "standard" 

# DETAILED MODE (comprehensive analysis with correlations):
# discord_report_level: "detailed"
